export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';


export const REQUEST__STARTED = 'REQUEST__STARTED';
export const REQUEST__FAILED = 'REQUEST__FAILED';
export const REQUEST__FINISHED = 'REQUEST__FINISHED';

export const LOGIN__REQUESTED = 'login-requested';
export const LOGIN__SUCCEEDED = 'login-succeeded';
export const LOGIN__FAILED = 'login-failed';
export const LOGIN__COMPLETED = 'login-completed';

export const LOGOUT__REQUESTED = 'logout-requested';
export const LOGOUT__COMPLETED = 'logout-completed';

export const CHANGE_PASSWORD__REQUESTED = 'CHANGE_PASSWORD__REQUESTED';
export const CHANGE_PASSWORD__SUCCEEDED = 'CHANGE_PASSWORD__SUCCEEDED';
export const CHANGE_PASSWORD__FAILED = 'CHANGE_PASSWORD__FAILED';

export const PROFILE__REQUESTED = 'PROFILE__REQUESTED';
export const PROFILE__REQUESTED__SUCCEEDED = 'PROFILE__REQUESTED__SUCCEEDED';
export const PROFILE__REQUESTED__FAILED = 'PROFILE__REQUESTED__FAILED';

export const REGISTRATION__REQUESTED = 'REGISTRATION__REQUESTED';
export const REGISTRATION__REQUESTED__SUCCEEDED = 'REGISTRATION__REQUESTED__SUCCEEDED';
export const REGISTRATION__REQUESTED__FAILED = 'REGISTRATION__REQUESTED__FAILED';

export const BLOGPOST__REQUESTED = 'BLOGPOST__REQUESTED';
export const BLOGPOST__REQUESTED__SUCCEEDED = 'BLOGPOST__REQUESTED__SUCCEEDED';
export const BLOGPOST__REQUESTED__FAILED = 'BLOGPOST__REQUESTED__FAILED';

export const BLOGPOSTS__REQUESTED = 'BLOGPOSTS__REQUESTED';
export const BLOGPOSTS__REQUESTED__SUCCEEDED = 'BLOGPOSTS__REQUESTED__SUCCEEDED';
export const BLOGPOSTS__REQUESTED__FAILED = 'BLOGPOSTS__REQUESTED__FAILED';

export const BLOGPOST__DELETED__REQUESTED = 'BLOGPOSTS__DELETED';
export const BLOGPOST__DELETED__SUCCEEDED = 'BLOGPOSTS__DELETED__SUCCEEDED';
export const BLOGPOST__DELETED__FAILED = 'BLOGPOST__DELETED__FAILED';

export const BLOGPOST__EDITED__REQUESTED = 'BLOGPOST__EDITED';
export const BLOGPOST__EDITED__SUCCEEDED = 'BLOGPOST__EDITED__SUCCEEDED';
export const BLOGPOST__EDITED__FAILED = 'BLOGPOST__EDITED__FAILED';
